spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:p6spy:mysql://${mysqlhost}/${mysqlSchema}?nullCatalogMeansCurrent=true&useUnicode=yes&characterEncoding=UTF-8
    username: ${mysqlUsername}
    password: ${mysqlPassword}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

okta:
  oauth2:
    issuer: ${oauth2Issuer}
    audience: ${oauth2Audience}
    scope-claim: scope

management:
  security:
    enabled: false

server:
  max-http-header-size: 32000

logging:
  level:
    org.springframework.data: debug
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.ellisdon.caas.contact: DEBUG
