spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: jdbc:p6spy:mysql://${mysqlhost}/${mysqlSchema}?nullCatalogMeansCurrent=true&useUnicode=yes&characterEncoding=UTF-8
    username: ${mysqlUsername}
    password: ${mysqlPassword}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
  security:
    enabled: false

logging:
  level:
    org.springframework: error
    com.ellisdon.caas: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor: trace

server:
  port: 9095
