spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  data:
    mongodb:
      database: SqlTailConfiguration
      uri: mongodb://${mongoUsername}:${mongoPassword}@${mongoHost}

  datasource:
    url: jdbc:p6spy:mysql://${mysqlhost}/${mysqlSchema}?nullCatalogMeansCurrent=true&useUnicode=yes&characterEncoding=UTF-8
    username: ${mysqlUsername}
    password: ${mysqlPassword}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  rabbitmq:
    host: ${rabbitMqHost}
    port: ${rabbitMqPort}
    username: ${rabbitMqUsername}
    password: ${rabbitMqPassword}

management:
  security:
    enabled: false

server:
  max-http-header-size: 32000

logging:
  level:
    org.springframework.data: debug
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.ellisdon.caas.sqltail: DEBUG
