spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

okta:
  oauth2:
    issuer: ${oauth2Issuer}
    audience: ${oauth2Audience}
    scope-claim: scope

database:
  sql:
    host: ${mysqlhost}
    port: 3306
    username: ${mysqlUsername}
    password: ${mysqlPassword}
    schema: ${mysqlSchema}

management:
  security:
    enabled: false

server:
  max-http-header-size: 32000

logging:
  level:
    org.springframework.data: debug
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.ellisdon.caas.contact: DEBUG
