spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  data:
    mongodb:
      database: SqlTailConfiguration
      uri: mongodb://localhost:27017

  datasource:
    url: jdbc:p6spy:mysql://${mysqlhost}/${mysqlSchema}?nullCatalogMeansCurrent=true&useUnicode=yes&characterEncoding=UTF-8
    username: ${mysqlUsername}
    password: ${mysqlPassword}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  task:
    scheduling:
      pool:
        size: 20

okta:
  oauth2:
    issuer: ${oauth2Issuer}
    audience: ${oauth2Audience}
    scope-claim: scope

management:
  security:
    enabled: false

logging:
  level:
    org.springframework.data: debug
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.ellisdon.caas.contact: DEBUG

server:
  max-http-header-size: 32000
  port: 9095
