{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sqltailservice.fullname" . -}}
{{- $serviceName := include "sqltailservice.name" . -}}
{{- $hostName := include "ingress.hostname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $serviceName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ $hostName | quote }}
    secretName: {{ .Values.ingress.secretName }}
{{- end }}
  rules:
    - host: {{ $hostName | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }} 
{{- end }}
